import Kasir.Kasir_Das;
import Pelanggan.Pelanggan_Layanan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class LOGIN extends javax.swing.JFrame {
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }
    
    
    public class DatabaseConnection {
    public static Connection getConnection() {
        Connection connection = null;
        try {
            String url = "jdbc:mysql://localhost:3306/cucianradja2"; // Ganti nama_database
            String username = "root"; // Username MySQL
            String password = ""; // Password MySQL
            connection = DriverManager.getConnection(url, username, password);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return connection;
    }
}
//sambungan yang dibawah
void bersih(){
    t_username.setText("Masukkan ID");
    t_password.setText("Password");
    role.setSelectedItem("Role");
}   


private void addCustomListener() {
    // Inisialisasi komponen
    lb_showpw = new JLabel(new ImageIcon(getClass().getResource("/img/Eye_1.png")));
    lb_hidepw = new JLabel(new ImageIcon(getClass().getResource("/img/Invisible_1.png")));
    t_password = new JPasswordField("Password");
    role = new JComboBox<>();
    role.addItem("Owner");
    role.addItem("Kasir");
    role.addItem("Pelanggan");

    // Atur password field
    t_username.setFont(new java.awt.Font("Segoe UI", 0, 14));
    t_username.setForeground(new java.awt.Color(204, 204, 204));
    t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    t_password.setEchoChar('*');
    t_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 255)));

    // Tambahkan MouseListener untuk ikon
    lb_showpw.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lb_showpwMouseClicked(evt);
        }
    });

    lb_hidepw.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lb_hidepwMouseClicked(evt);
        }
    });

    // Atur visibilitas awal
    lb_showpw.setVisible(true);
    lb_hidepw.setVisible(false);

    // Tambahkan komponen ke panel
    jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 203, 33));
    jPanel1.add(lb_showpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 30, 30));
    jPanel1.add(lb_hidepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 30, 30));
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        lb_showpw = new javax.swing.JLabel();
        lb_hidepw = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        role = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Password_3.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 30));

        t_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_username.setForeground(new java.awt.Color(51, 51, 51));
        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("Masukkan ID");
        t_username.setBorder(null);
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 203, 33));

        lb_showpw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Invisible_1.png"))); // NOI18N
        lb_showpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showpwMouseClicked(evt);
            }
        });
        jPanel1.add(lb_showpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 30, 30));

        lb_hidepw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Eye_1.png"))); // NOI18N
        lb_hidepw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hidepwMouseClicked(evt);
            }
        });
        jPanel1.add(lb_hidepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, 30));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Forgot Password?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        t_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_password.setText("Password");
        t_password.setBorder(null);
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, 30));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "owner", "kasir", "pelanggan" }));
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_1-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 380));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle2.setText("LOGIN");
        rSMaterialButtonRectangle2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 110, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/POPP.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(768, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String Password=t_password.getText();
        if(Password.equals("")||Password.equals("Password")){
            t_password.setText("Password");
        }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String pass=t_password.getText();
        if (pass.equals("Password")){
            t_password.setText("");
        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // Membuka form ForgotPassword
        Forgotpass forgotPassword = new Forgotpass(); // Buat instance form
        forgotPassword.setVisible(true); // Tampilkan form ForgotPassword
        this.dispose(); // Tutup form LOGIN (opsional)
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lb_hidepwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hidepwMouseClicked
        lb_showpw.setVisible(true);  // Menampilkan ikon "show password"
        lb_hidepw.setVisible(false); // Menyembunyikan ikon "hide password"
        t_password.setEchoChar('*');
    }//GEN-LAST:event_lb_hidepwMouseClicked

    private void lb_showpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showpwMouseClicked
        // Menyembunyikan ikon show password
        lb_showpw.setVisible(false);
        // Menampilkan ikon hide password
        lb_hidepw.setVisible(true);
        // Menampilkan password (menghapus karakter masking)
        t_password.setEchoChar((char)0);
    }//GEN-LAST:event_lb_showpwMouseClicked

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String Username=t_username.getText();
        if(Username.equals("")||Username.equals("Masukkan ID")){
            t_username.setText("Masukkan ID");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String Username=t_username.getText();
        if (Username.equals("Masukkan ID")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
   String id_pelangganStr = t_username.getText().trim(); // Ambil input ID Pelanggan sebagai String
    String password = String.valueOf(t_password.getPassword()).trim(); // Ambil password dan hapus spasi berlebih
    String roleStr = role.getSelectedItem().toString().trim(); // Ambil input Role sebagai String

    if (id_pelangganStr.isEmpty() || password.isEmpty() || roleStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID, Password, dan Role tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Konversi ID Pelanggan ke tipe integer
        int id_pelanggan = Integer.parseInt(id_pelangganStr); // Pastikan input adalah angka

        // Koneksi ke database dan validasi data
        try (Connection connection = DatabaseConnection.getConnection()) {
            String query = "SELECT * FROM user WHERE id_user = ? AND password = ? AND role = ?";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setInt(1, id_pelanggan); // Gunakan metode `setInt` untuk ID Pelanggan
            pst.setString(2, password); // Gunakan metode `setString` untuk password
            pst.setString(3, roleStr); // Gunakan metode `setString` untuk Role

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Jika data cocok, buka form sesuai dengan role
                JOptionPane.showMessageDialog(this, "Login berhasil!");
                switch (roleStr.toLowerCase()) { // Periksa role dengan case-insensitive
                    case "owner" -> new Owner().setVisible(true); // Ganti `Owner` dengan nama form Owner
                    case "kasir" -> new Kasir_Das().setVisible(true); // Ganti `Kasir` dengan nama form Kasir
                    case "pelanggan" -> new Pelanggan_Layanan().setVisible(true); // Ganti `Pelanggan` dengan nama form Kasir
                    default -> {
                        JOptionPane.showMessageDialog(this, "Role tidak dikenal!", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                // Periksa role dengan case-insensitive
                this.dispose(); // Tutup form login
            } else {
                // Jika data tidak cocok
                JOptionPane.showMessageDialog(this, "ID Pelanggan, Password, atau Role salah!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        // Jika input ID Pelanggan tidak bisa dikonversi ke integer
        JOptionPane.showMessageDialog(this, "ID Pelanggan harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Menangani error koneksi atau query
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghubungkan ke database!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_hidepw;
    private javax.swing.JLabel lb_showpw;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
