/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.SimpleDateFormat;




/**
 *
 * @author ACER
 */
public class Owner_StokInput extends javax.swing.JFrame {

    /**
     * Creates new form Kasir_StokIn
     */
    public Owner_StokInput() {
        setUndecorated(true);
        initComponents();
        loadTable();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setCurrentDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public class DatabaseConnection {
    public static Connection getConnection() {
        Connection connection = null;
        try {
            String url = "jdbc:mysql://localhost:3306/cucianradja2"; // Ganti nama_database
            String username = "root"; // Username MySQL
            String password = ""; // Password MySQL
            connection = DriverManager.getConnection(url, username, password);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return connection;
    }
}

    
       
       // Memuat data ke JTable
private void loadTable() {
    // Model untuk JTable
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"ID Stok", "Nama Stok", "Jumlah Stok", "Harga Stok", "Tanggal Stok"}, 
        0
    );
    String query = "SELECT * FROM stok";

    try (Connection conn = Owner_StokInput.DatabaseConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            // Membaca data dari ResultSet
            int id_s = rs.getInt("id_stok");
            String nama_s = rs.getString("nama_stok");
            int jml_s = rs.getInt("jumlah_stok");
            int idk = rs.getInt("harga_stok");
            String tgl = rs.getString("tanggal_stok");

            // Menambahkan data ke model
            model.addRow(new Object[]{id_s, nama_s, jml_s, idk, tgl});
        }

        // Atur model ke JTable
        tabel_stok.setModel(model);
        
        setAutoIncrementId();

        // Atur ukuran kolom dan pengaturan lainnya
        Tabel(tabel_stok, new int[]{100, 150, 150, 150, 250, 150});


    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Gagal memuat data: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}


// Mengatur ukuran kolom JTable
private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);  // Nonaktifkan auto-resize
    int kolom = tb.getColumnCount();
    
    // Menyesuaikan ukuran kolom sesuai lebar yang diberikan
    for (int i = 0; i < kolom; i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);  // Set lebar kolom
    }

    tb.setRowHeight(25);  // Menetapkan tinggi baris
}

// Model default untuk JTable
private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
    return new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"ID Stok", "Nama Stok", "Jumlah Stok", "Harga Stok", "Tanggal Stok"}
    ) {
        boolean[] canEdit = new boolean[] {
            false, false, false, false, false  // Kolom tidak dapat diedit
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
}

private void setAutoIncrementId() {
    String query = "SELECT MAX(id_stok) AS last_id FROM stok";

    try (Connection conn = Owner_StokInput.DatabaseConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {
        
        if (rs.next()) {
            int lastId = rs.getInt("last_id");
            int nextId = lastId + 1; // Tambahkan 1 ke ID terakhir
            txt_ids.setText(String.valueOf(nextId));
        } else {
            txt_ids.setText("1"); // Jika tidak ada data, mulai dari 1
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengambil ID terakhir: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}


private void setCurrentDate() {
    // Mendapatkan tanggal saat ini
    Date currentDate = new Date(System.currentTimeMillis());
    
    // Menampilkan tanggal ke TextField dalam format yyyy-MM-dd
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    tglStok.setText(sdf.format(currentDate)); // Format sesuai kebutuhan
}



 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Mid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_jmlStok = new javax.swing.JTextField();
        txt_hargaStok = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        t_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txt_namaStok = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_ids = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tglStok = new javax.swing.JTextField();
        Left = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Dashboard4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Top.setBackground(new java.awt.Color(255, 255, 255));

        lg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout_1.png"))); // NOI18N
        lg.setText("LOGOUT");
        lg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lgMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo cucian eric baru.png"))); // NOI18N

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lg)
                .addGap(20, 20, 20))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lg)
                .addGap(23, 23, 23))
        );

        Mid.setBackground(new java.awt.Color(93, 173, 226));
        Mid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Input Data Stok");
        Mid.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Data Stok");
        Mid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 21, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama Stok");
        Mid.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jumlah Stok");
        Mid.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga Stok");
        Mid.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txt_jmlStok.setText("2");
        Mid.add(txt_jmlStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, -1));

        txt_hargaStok.setText("1000");
        txt_hargaStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaStokActionPerformed(evt);
            }
        });
        Mid.add(txt_hargaStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, -1));

        btn_simpan.setBackground(new java.awt.Color(51, 0, 204));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save_1.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        Mid.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 329, -1, -1));

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete Trash.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        Mid.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 329, -1, -1));

        btn_kembali.setBackground(new java.awt.Color(102, 255, 0));
        btn_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Go Back.png"))); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        Mid.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 329, -1, -1));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search_1.png"))); // NOI18N
        searchButton.setContentAreaFilled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        Mid.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 70, 40, 30));

        t_cari.setText("Cari Nama Stok");
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        Mid.add(t_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 66, 356, 37));

        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Stok", "Jumlah Stok", "Harga Stok"
            }
        ));
        tabel_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_stokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_stok);

        Mid.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 466, 279));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Refresh.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Mid.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 40, 30));

        txt_namaStok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sabun Cuci/ML", "Kompon/Gram", "Kanebo", "Penghitam/ML" }));
        txt_namaStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaStokActionPerformed(evt);
            }
        });
        Mid.add(txt_namaStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel11.setText("ID Stok");
        Mid.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_ids.setEnabled(false);
        Mid.add(txt_ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        jLabel6.setText("Tanggal Input Stok");
        Mid.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        tglStok.setEnabled(false);
        Mid.add(tglStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        Left.setBackground(new java.awt.Color(44, 46, 141));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dashboard Layout.png"))); // NOI18N
        jLabel17.setText("     Dashboard");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Price Tag.png"))); // NOI18N
        jLabel26.setText("     Layanan & Harga");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer.png"))); // NOI18N
        jLabel18.setText("     Pelanggan");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Discount.png"))); // NOI18N
        jLabel27.setText("     Diskon Spesial");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Transaction.png"))); // NOI18N
        jLabel29.setText("     Riwayat Transaksi");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Caretaker_1.png"))); // NOI18N

        Dashboard4.setBackground(new java.awt.Color(51, 51, 255));
        Dashboard4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sell Stock.png"))); // NOI18N
        jLabel32.setText("     Stok");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Dashboard4Layout = new javax.swing.GroupLayout(Dashboard4);
        Dashboard4.setLayout(Dashboard4Layout);
        Dashboard4Layout.setHorizontalGroup(
            Dashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Dashboard4Layout.setVerticalGroup(
            Dashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Name.png"))); // NOI18N
        jLabel42.setText("     User");
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report_2.png"))); // NOI18N
        jLabel43.setText("     Laporan");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Service.png"))); // NOI18N
        jLabel44.setText("     Maintance");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LeftLayout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(10, 10, 10)
                .addComponent(jLabel42)
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Dashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43)
                .addGap(12, 12, 12)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public static void openForm(){
        Owner ownerForm = new Owner();
        ownerForm.setVisible(true);
    }
    
    public static void openFormPelanggan(){
        Owner_Pelanggan ownerForm = new Owner_Pelanggan();
        ownerForm.setVisible(true);
    }
    
    public static void openFormKaryawan(){
        Owner_Karyawan ownerForm = new Owner_Karyawan();
        ownerForm.setVisible(true);
    }
    
    public static void openFormLayanan(){
        Owner_Layanan ownerForm = new Owner_Layanan();
        ownerForm.setVisible(true);
    }
    
    public static void openFormDiskon(){
        Owner_Diskon ownerForm = new Owner_Diskon();
        ownerForm.setVisible(true);
    }
    
    public static void openFormStok(){
        Owner_Stok ownerForm = new Owner_Stok();
        ownerForm.setVisible(true);
    }
    
    public static void openFormRiwayat(){
        Owner_Transaksi ownerForm = new Owner_Transaksi();
        ownerForm.setVisible(true);
    }
    
    public static void openFormReport(){
        Report ownerForm = new Report();
        ownerForm.setVisible(true);
    }
    
    public static void openFormUser(){
        Owner_User ownerForm = new Owner_User();
        ownerForm.setVisible(true);
    }
    private void lgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMousePressed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );
        if (response == JOptionPane.YES_OPTION) {
            // Lakukan tindakan logout, misalnya kembali ke halaman login
            System.out.println("Logout Berhasil");
            System.exit(0); // Menutup aplikasi (opsional)
        }

        this.dispose(); // Menutup form saat ini
        setVisible(true);
    }//GEN-LAST:event_lgMousePressed

    private void txt_hargaStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaStokActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    // Mendapatkan nilai dari TextField dan ComboBox
    String idStokStr = txt_ids.getText();
    String namaStokStr = txt_namaStok.getSelectedItem().toString();
    String jmlStokStr = txt_jmlStok.getText();
    String hargaStokStr = txt_hargaStok.getText();
    String tglStokStr = tglStok.getText(); // Mendapatkan tanggal stok dari TextField

    // Validasi jika field kosong
    if (idStokStr.isEmpty() || namaStokStr.isEmpty() || jmlStokStr.isEmpty() || hargaStokStr.isEmpty() || tglStokStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validasi input numerik untuk jumlah stok dan harga stok
    try {
        int jumlahStok = Integer.parseInt(jmlStokStr);  // Mengubah String ke Integer
        double hargaStok = Double.parseDouble(hargaStokStr);  // Mengubah String ke Double

        // Validasi format tanggal
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Date parsedDate = sdf.parse(tglStokStr); // Parsing tanggal dari TextField
        java.sql.Date tglStoks = new java.sql.Date(parsedDate.getTime()); // Konversi ke java.sql.Date

        // Cek apakah nama stok sudah ada
        String checkQuery = "SELECT jumlah_stok, harga_stok, tanggal_stok FROM stok WHERE nama_stok = ?";

        try (Connection conn = Owner_StokInput.DatabaseConnection.getConnection();
             PreparedStatement checkPs = conn.prepareStatement(checkQuery)) {

            checkPs.setString(1, namaStokStr);
            try (ResultSet rs = checkPs.executeQuery()) {
                if (rs.next()) {
                    // Jika stok sudah ada, update jumlah stok, harga stok, dan tanggal stok
                    int existingJumlahStok = rs.getInt("jumlah_stok");
                    double existingHargaStok = rs.getDouble("harga_stok");
                    java.sql.Date existingTglStoks = rs.getDate("tanggal_stok");

                    // Update stok dan harga
                    String updateQuery = "UPDATE stok SET jumlah_stok = ?, harga_stok = ?, tanggal_stok = ? WHERE nama_stok = ?";
                    try (PreparedStatement updatePs = conn.prepareStatement(updateQuery)) {
                        updatePs.setInt(1, existingJumlahStok + jumlahStok); // Tambah jumlah stok
                        updatePs.setDouble(2, existingHargaStok + hargaStok); // Tambah harga stok
                        updatePs.setDate(3, tglStoks); // Update tanggal stok
                        updatePs.setString(4, namaStokStr);

                        int rowsUpdated = updatePs.executeUpdate();
                        if (rowsUpdated > 0) {
                            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                } else {
                    // Jika stok belum ada, insert data baru
                    String insertQuery = "INSERT INTO stok (id_stok, nama_stok, jumlah_stok, harga_stok, tanggal_stok) VALUES (?, ?, ?, ?, ?)";
                    try (PreparedStatement insertPs = conn.prepareStatement(insertQuery)) {
                        insertPs.setString(1, idStokStr);
                        insertPs.setString(2, namaStokStr);
                        insertPs.setInt(3, jumlahStok);
                        insertPs.setDouble(4, hargaStok);
                        insertPs.setDate(5, tglStoks);  // Menyimpan tanggal stok

                        int rowsInserted = insertPs.executeUpdate();
                        if (rowsInserted > 0) {
                            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            }

            // Mendapatkan tanggal saat ini untuk reset
            java.util.Date currentDate = new java.util.Date();  // Mendapatkan tanggal saat ini
            sdf = new java.text.SimpleDateFormat("yyyy-MM-dd"); // Format yang digunakan
            tglStok.setText(sdf.format(currentDate)); // Reset Tanggal Stok ke tanggal saat ini

            // Membersihkan field setelah sukses
            txt_ids.setText(""); // Reset ID Stok
            txt_namaStok.setSelectedIndex(0); // Reset ComboBox
            txt_jmlStok.setText(""); // Reset Jumlah Stok
            txt_hargaStok.setText(""); // Reset Harga Stok

        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Jumlah stok dan harga stok harus berupa angka!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (java.text.ParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Format tanggal tidak valid! Gunakan format yyyy-mm-dd.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // Pastikan pengguna memilih baris di JTable
        int selectedRow = tabel_stok.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Mendapatkan nilai dari kolom yang relevan, misalnya "id_stok"
        String idStokStr = tabel_stok.getValueAt(selectedRow, 0).toString(); // Sesuaikan indeks kolom

        // Konversi idStokStr menjadi integer jika diperlukan
        int idStok;
        try {
            idStok = Integer.parseInt(idStokStr); // Pastikan id_stok adalah integer di database
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID stok tidak valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konfirmasi penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus data dengan ID stok: " + idStok + "?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try (Connection conn = Owner_StokInput.DatabaseConnection.getConnection();
                PreparedStatement ps = conn.prepareStatement("DELETE FROM stok WHERE id_stok = ?")) {

                // Set parameter query
                ps.setInt(1, idStok);

                // Eksekusi query
                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    loadTable(); // Refresh tabel setelah penghapusan
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        Owner_Stok owner_stokinput = new Owner_Stok(); // Buat instance form
        owner_stokinput.setVisible(true); // Tampilkan form ForgotPassword
        this.dispose(); // Tutup form LOGIN (opsional)
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String cari = t_cari.getText().trim();  // Mengambil ID yang dicari dari TextField

        if (cari.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap masukkan ID yang ingin dicari!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Tidak lanjutkan jika field kosong
        }

        // Menghapus semua data lama di JTable
        DefaultTableModel model = (DefaultTableModel) tabel_stok.getModel();
        model.setRowCount(0); // Menghapus semua baris sebelumnya

        try (Connection conn = Owner_StokInput.DatabaseConnection.getConnection()) {
            // Menggunakan PreparedStatement untuk menghindari SQL injection
            String sql = "SELECT * FROM stok WHERE nama_stok LIKE ?";
            try (PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, "%" + cari + "%");  // Menggunakan wildcard untuk pencarian yang lebih fleksibel

                try (ResultSet rs = pst.executeQuery()) {
                    boolean found = false;  // Flag untuk mengecek jika ada hasil pencarian
                    while (rs.next()) {
                        // Menampilkan hasil pencarian ke field yang sesuai
                        txt_ids.setText(rs.getString("id_stok"));  // id transaksi
                        txt_namaStok.setSelectedItem(rs.getString("nama_stok"));  // id transaksi
                        txt_jmlStok.setText(rs.getString("jumlah_stok"));  // id paket
                        txt_hargaStok.setText(rs.getString("harga_stok"));  // id karyawan

                        // Mengaktifkan field untuk diubah
                        txt_namaStok.setEnabled(false);
                        txt_namaStok.setEnabled(true);
                        txt_jmlStok.setEnabled(true);
                        txt_hargaStok.setEnabled(true);

                        // Menambahkan hasil pencarian ke JTable
                        model.addRow(new Object[]{
                            rs.getString("id_stok"), // ID Transaksi
                            rs.getString("nama_stok"), // ID Transaksi
                            rs.getString("jumlah_stok"),     // ID Paket
                            rs.getString("harga_stok"),  // ID Karyawan
                        });
                        found = true;  // Tandakan bahwa data ditemukan
                    }

                    // Jika tidak ada data ditemukan
                    if (!found) {
                        JOptionPane.showMessageDialog(null, "Maaf...Data tidak ditemukan", "Pencarian Gagal", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Terjadi Kesalahan: " + e);
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat melakukan pencarian.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Reset tombol dan text field setelah pencarian
        searchButton.setText("");
        btn_simpan.setEnabled(true);
        btn_hapus.setEnabled(true);
        btn_kembali.setEnabled(true);

    }//GEN-LAST:event_searchButtonActionPerformed

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        String Username=t_cari.getText();
        if (Username.equals("Cari Nama Stok")){
            t_cari.setText("");
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        String Username=t_cari.getText();
        if(Username.equals("")||Username.equals("Cari Nama Stok")){
            t_cari.setText("Cari Nama Stok");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void tabel_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_stokMouseClicked
        if(evt.getClickCount()==1){
            Tampil();
        }
    }//GEN-LAST:event_tabel_stokMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_namaStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaStokActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        Owner.openForm();
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        Owner.openFormLayanan();
        dispose();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        Owner.openFormPelanggan();
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        Owner.openFormDiskon();
        dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        Owner.openFormRiwayat();
        dispose();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        Owner.openFormStok();
        dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:       
        Owner.openFormUser();
        dispose();
    }//GEN-LAST:event_jLabel42MouseClicked
int row = 0;
    public void Tampil(){
        row = tabel_stok.getSelectedRow();
        txt_ids.setText(tabel_stok.getValueAt(row,0).toString());
        txt_namaStok.setSelectedItem(tabel_stok.getValueAt(row,1).toString());
        txt_jmlStok.setText(tabel_stok.getValueAt(row,2).toString());
        txt_hargaStok.setText(tabel_stok.getValueAt(row,3).toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner_StokInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner_StokInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner_StokInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner_StokInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_StokInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard4;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Mid;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lg;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTable tabel_stok;
    private javax.swing.JTextField tglStok;
    private javax.swing.JTextField txt_hargaStok;
    private javax.swing.JTextField txt_ids;
    private javax.swing.JTextField txt_jmlStok;
    private javax.swing.JComboBox<String> txt_namaStok;
    // End of variables declaration//GEN-END:variables
}
